name: PR
description: Validate PR

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  install-deps:
    name: Install deps
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install

  lint:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
